// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6K126H-OLSvP0QUmkQuNBwPYwf8TTSrg',
    appId: '1:952825045607:web:aa58805f332f382be6eac2',
    messagingSenderId: '952825045607',
    projectId: 'booo-booo-booo-e9c6c',
    authDomain: 'booo-booo-booo-e9c6c.firebaseapp.com',
    storageBucket: 'booo-booo-booo-e9c6c.firebasestorage.app',
    measurementId: 'G-895ZDJ19ZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUN5HB8wzz1zHwJ85ex0d1T-zIozOTZw0',
    appId: '1:952825045607:android:94ab9eb55eeba5c9e6eac2',
    messagingSenderId: '952825045607',
    projectId: 'booo-booo-booo-e9c6c',
    storageBucket: 'booo-booo-booo-e9c6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvkEmsrLUwXCd3WRnYJ-RY1NvA8RLt26A',
    appId: '1:952825045607:ios:9c267d48d334726de6eac2',
    messagingSenderId: '952825045607',
    projectId: 'booo-booo-booo-e9c6c',
    storageBucket: 'booo-booo-booo-e9c6c.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvkEmsrLUwXCd3WRnYJ-RY1NvA8RLt26A',
    appId: '1:952825045607:ios:9c267d48d334726de6eac2',
    messagingSenderId: '952825045607',
    projectId: 'booo-booo-booo-e9c6c',
    storageBucket: 'booo-booo-booo-e9c6c.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6K126H-OLSvP0QUmkQuNBwPYwf8TTSrg',
    appId: '1:952825045607:web:a7e3c69bceffe1cce6eac2',
    messagingSenderId: '952825045607',
    projectId: 'booo-booo-booo-e9c6c',
    authDomain: 'booo-booo-booo-e9c6c.firebaseapp.com',
    storageBucket: 'booo-booo-booo-e9c6c.firebasestorage.app',
    measurementId: 'G-CZ5RMVWW61',
  );

}